# Generated by Django 2.0.2 on 2019-11-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourinoAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.TextField()),
                ('role', models.CharField(choices=[('A', 'Admin'), ('T', 'TourLeader'), ('S', 'Seller'), ('B', 'Blogger')], max_length=1)),
            ],
        ),
    ]
