# Generated by Django 2.0.2 on 2019-11-25 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TourinoAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptype', models.CharField(choices=[('C', 'Craft'), ('A', 'Agricultural'), ('F', 'Fruit')], default='S', max_length=1)),
                ('name', models.CharField(max_length=55, unique=True)),
                ('price', models.DecimalField(decimal_places=7, max_digits=20)),
                ('image_url', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourinoAdmin.TourinoAdmin')),
            ],
        ),
    ]
