# Generated by Django 2.0.2 on 2019-11-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourinoAdmin', '0003_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
