# Generated by Django 2.0.2 on 2019-11-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourinoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.TextField()),
                ('news', models.BooleanField(default=False)),
            ],
        ),
    ]
