# Generated by Django 2.0.2 on 2019-11-25 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TourinoAdmin', '0005_post'),
        ('TourinoUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('comment', models.TextField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TourinoAdmin.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TourinoUser.TourinoUser')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourinoAdmin.Product')),
            ],
        ),
        migrations.CreateModel(
            name='TourComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('comment', models.TextField()),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TourinoAdmin.Tour')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TourinoUser.TourinoUser')),
            ],
        ),
        migrations.CreateModel(
            name='TourSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourinoAdmin.Tour')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=9, max_digits=20, null=True)),
                ('products', models.ManyToManyField(blank=True, null=True, through='TourinoUser.ProductSell', to='TourinoAdmin.Product')),
                ('tours', models.ManyToManyField(blank=True, null=True, through='TourinoUser.TourSell', to='TourinoAdmin.Tour')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TourinoUser.TourinoUser')),
            ],
        ),
        migrations.AddField(
            model_name='toursell',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourinoUser.Wallet'),
        ),
        migrations.AddField(
            model_name='productsell',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourinoUser.Wallet'),
        ),
    ]
