# Generated by Django 2.0.2 on 2019-11-27 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TourinoUser', '0002_auto_20191125_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourcomment',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourinoAdmin.Tour'),
        ),
        migrations.AlterField(
            model_name='tourcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourinoUser.TourinoUser'),
        ),
    ]
