# Generated by Django 2.0.2 on 2019-12-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourinoUser', '0004_auto_20191127_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourinouser',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
