# Generated by Django 2.0.2 on 2019-12-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourinoUser', '0005_auto_20191222_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourinouser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
